// Port of `DomLayout` and its derived-geometry helpers in
// crates/obscura-render/src/dom.rs.
using Obscura.Dom;

namespace Obscura.Render;

internal enum GeneratedBoxKind : byte
{
    Before,
    After,
}

internal readonly record struct GeneratedBox(NodeId Host, GeneratedBoxKind Kind, Rect Rect);

internal readonly record struct GeneratedBoxBuild(
    NodeId Host,
    GeneratedBoxKind Kind,
    Layout.NodeId Node);

/// <summary>
/// Style maps moved out of a previous layout. Moving, rather than cloning, keeps incremental
/// restyle from retaining a second heap-heavy LayoutStyle graph beside the final used styles.
/// </summary>
internal sealed class RetainedStyleMaps
{
    internal required Dictionary<NodeId, LayoutStyle> Styles { get; init; }

    internal required Dictionary<NodeId, IReadOnlyDictionary<string, string>> CustomProperties { get; init; }
}

/// <summary>Per-element border boxes after layout, in viewport coordinates.</summary>
public sealed class DomLayout
{
    /// <summary>Border boxes keyed by DOM node.</summary>
    public Dictionary<NodeId, Rect> Rects { get; internal set; } = [];

    /// <summary>
    /// Per-line border-box fragments for ordinary non-replaced inline elements.
    /// <see cref="Rects"/> retains their union for <c>getBoundingClientRect()</c>; this list
    /// is the source for background/border painting and <c>getClientRects()</c>.
    /// </summary>
    public Dictionary<NodeId, List<Rect>> InlineFragments { get; internal set; } = [];

    /// <summary>Computed style per element.</summary>
    public Dictionary<NodeId, LayoutStyle> Styles { get; internal set; } = [];

    /// <summary>
    /// Computed custom properties in force for each element. Values are shared because the
    /// overwhelmingly common case is inheritance without an override.
    /// </summary>
    public Dictionary<NodeId, IReadOnlyDictionary<string, string>> CustomProperties { get; internal set; } = [];

    /// <summary>
    /// The per-axis clip inherited from ancestor non-visible overflow, keyed per node, in
    /// SCREEN space. <c>null</c> means unclipped. Does not include the node's own overflow.
    /// </summary>
    public Dictionary<NodeId, OverflowClip?> ClipRects { get; internal set; } = [];

    /// <summary>
    /// Accumulated <c>transform: translate()</c> per node (own + ancestors), in CSS px. Only
    /// nodes with a non-zero accumulation are present.
    /// </summary>
    public Dictionary<NodeId, (float X, float Y)> Translates { get; internal set; } = [];

    /// <summary>
    /// Accumulated authored transforms in immutable document coordinates. Entries exist only
    /// inside a non-identity transformed subtree.
    /// </summary>
    public Dictionary<NodeId, Affine2> Transforms { get; internal set; } = [];

    /// <summary>
    /// Per-word geometry for text nodes: a text DOM node lays out as one taffy leaf per word,
    /// so its rendered content is a list of (box, word text) pairs.
    /// </summary>
    public Dictionary<NodeId, List<(Rect Rect, string Text)>> TextRuns { get; internal set; } = [];

    /// <summary>
    /// Inline formatting contexts shaped by the text engine: a single leaf per container, its
    /// glyphs held in <see cref="TextEngine"/>.
    /// </summary>
    public TextEngine TextEngine { get; internal set; } = new();

    /// <summary>Container node to shaped item index.</summary>
    public Dictionary<NodeId, int> IfcItems { get; internal set; } = [];

    /// <summary>
    /// Anonymous inline-run contexts: a mixed block's consecutive inline children folded to
    /// one shaped leaf each. Keyed by the parent block.
    /// </summary>
    public Dictionary<NodeId, List<int>> RunIfcItems { get; internal set; } = [];

    /// <summary>
    /// Webfont-shaped items backing the general per-word fallback, keyed by their real DOM
    /// text node so they can paint in exact tree order.
    /// </summary>
    public Dictionary<NodeId, List<int>> WordIfcItems { get; internal set; } = [];

    /// <summary>
    /// Anonymous in-flow boxes generated by <c>::before</c>/<c>::after</c>.
    /// </summary>
    internal List<GeneratedBox> GeneratedBoxes { get; set; } = [];

    /// <summary>Move the retained style maps out of this layout.</summary>
    internal RetainedStyleMaps TakeRetainedStyleMaps()
    {
        RetainedStyleMaps maps = new()
        {
            Styles = Styles,
            CustomProperties = CustomProperties,
        };
        Styles = [];
        CustomProperties = [];
        return maps;
    }

    internal DerivedLayoutState DerivedLayoutState(DomTree tree, (float Width, float Height) viewport)
    {
        HashSet<NodeId> viewportFixed = ViewportFixedNodes(tree);
        DerivedGeometryState geometry = DerivedGeometryWithFixed(tree, viewport, viewportFixed);
        return new DerivedLayoutState
        {
            ContentSize = geometry.ContentSize,
            ViewportFixed = viewportFixed,
            Sticky = geometry.Sticky,
            ScrollTree = geometry.ScrollTree,
        };
    }

    internal DerivedGeometryState DerivedGeometryWithFixed(
        DomTree tree,
        (float Width, float Height) viewport,
        HashSet<NodeId> viewportFixed)
    {
        (float Width, float Height) contentSize =
            ScrollingContentSizeWithFixed(tree, viewport, viewportFixed);
        ScrollTree scrollTree = BuildScrollTree(tree, viewport, contentSize, viewportFixed);
        StickyLayout sticky = StickyLayoutWithGeometry(tree, viewport, contentSize, scrollTree);
        return new DerivedGeometryState
        {
            ContentSize = contentSize,
            Sticky = sticky,
            ScrollTree = scrollTree,
        };
    }

    /// <summary>
    /// Refresh the derived paint-culling bit after an opacity-only sample.
    /// </summary>
    /// <remarks>
    /// Opacity stays a binary zero ancestor flag instead of multiplying the chain, which
    /// avoids underflow making a deep fractional-opacity subtree incorrectly disappear.
    /// </remarks>
    internal void RefreshEffectiveVisibility(DomTree tree)
    {
        Dictionary<NodeId, (bool VisibilityHidden, bool OpacityZero)> inherited = [];
        foreach (NodeId id in DomTraversal.RenderedDescendants(tree, tree.Document))
        {
            (bool VisibilityHidden, bool OpacityZero) parentState = (false, false);
            if (DomTraversal.RenderedParent(tree, id) is { } parent
                && inherited.TryGetValue(parent, out var found))
            {
                parentState = found;
            }

            if (!Styles.TryGetValue(id, out LayoutStyle? style))
            {
                inherited[id] = parentState;
                continue;
            }

            bool visibilityHidden = style.VisibilityHidden ?? parentState.VisibilityHidden;
            bool opacityZero = parentState.OpacityZero || style.Opacity is { } opacity && opacity <= 0f;
            style.EffectivelyInvisible = visibilityHidden || opacityZero;
            if (style.BeforePseudo is { } before)
            {
                before.EffectivelyInvisible = style.EffectivelyInvisible;
            }

            if (style.AfterPseudo is { } after)
            {
                after.EffectivelyInvisible = style.EffectivelyInvisible;
            }

            inherited[id] = (visibilityHidden, opacityZero);
        }
    }

    /// <summary>
    /// Rebuild visual geometry after a transform-only animation sample while retaining
    /// normal-flow boxes and shaped text.
    /// </summary>
    internal void RefreshVisualGeometry(DomTree tree, (float Width, float Height) viewport)
    {
        ClipRects.Clear();
        Translates.Clear();
        Transforms.Clear();

        NodeId? root = null;
        foreach (NodeId id in DomTraversal.RenderedDescendants(tree, tree.Document))
        {
            if (tree.GetNode(id)?.IsElement == true)
            {
                root = id;
                break;
            }
        }

        if (root is { } rootId)
        {
            float rootFontSize = Styles.TryGetValue(rootId, out LayoutStyle? rootStyle)
                ? rootStyle.FontSize ?? 16f
                : 16f;
            DomTransforms.ResolveClipRects(
                tree,
                rootId,
                null,
                0f,
                0f,
                Rects,
                Styles,
                ClipRects,
                Translates,
                Affine2.Identity,
                Transforms,
                rootFontSize,
                viewport);
        }

        foreach ((NodeId node, int item) in IfcItems)
        {
            TextEngine.SetClip(
                item,
                LayoutDomInternals.ShapedItemClip(node, Rects, Styles, ClipRects, Translates, viewport));
        }

        foreach ((NodeId parent, List<int> items) in RunIfcItems)
        {
            Rect? clip = LayoutDomInternals.ShapedItemClip(
                parent, Rects, Styles, ClipRects, Translates, viewport);
            foreach (int item in items)
            {
                TextEngine.SetClip(item, clip);
            }
        }

        foreach ((NodeId textNode, List<int> items) in WordIfcItems)
        {
            Rect? clip = LayoutDomInternals.ShapedItemClip(
                textNode, Rects, Styles, ClipRects, Translates, viewport);
            foreach (int item in items)
            {
                TextEngine.SetClip(item, clip);
            }
        }
    }

    /// <summary>
    /// Nodes whose painted coordinate space is anchored to the initial containing block.
    /// </summary>
    public HashSet<NodeId> ViewportFixedNodes(DomTree tree)
    {
        HashSet<NodeId> fixedNodes = [];
        Dictionary<NodeId, bool> hasFixedCb = [];

        foreach (NodeId id in DomTraversal.RenderedDescendants(tree, tree.Document))
        {
            NodeId? parent = DomTraversal.RenderedParent(tree, id);
            bool parentIsFixed = parent is { } p && fixedNodes.Contains(p);
            bool ancestorHasFixedCb = parent is { } q && hasFixedCb.TryGetValue(q, out bool value) && value;
            Styles.TryGetValue(id, out LayoutStyle? style);
            bool startsViewportFixed = style is not null && style.PositionFixed && !ancestorHasFixedCb;

            if (parentIsFixed || startsViewportFixed)
            {
                fixedNodes.Add(id);
            }

            bool establishesFixedCb = style is not null && style.ContainingBlockTriggers != 0;
            hasFixedCb[id] = ancestorHasFixedCb || establishesFixedCb;
        }

        return fixedNodes;
    }

    /// <summary>
    /// Build the dense element-scroll topology and local scrolling overflow.
    /// </summary>
    internal ScrollTree BuildScrollTree(
        DomTree tree,
        (float Width, float Height) viewport,
        (float Width, float Height) rootContentSize,
        HashSet<NodeId> viewportFixed)
    {
        List<NodeId> nodes = DomTraversal.RenderedDescendants(tree, tree.Document);
        int nodeCapacity = 0;
        foreach (NodeId id in nodes)
        {
            nodeCapacity = Math.Max(nodeCapacity, id.Index + 1);
        }

        ScrollId?[] nodeContainer = new ScrollId?[nodeCapacity];
        ScrollId?[] movementOwner = new ScrollId?[nodeCapacity];
        (float Width, float Height)?[] nodeContentSize = new (float, float)?[nodeCapacity];
        List<ScrollContainer> containers =
        [
            new ScrollContainer
            {
                Node = null,
                Parent = null,
                ClientSize = viewport,
                ContentSize = rootContentSize,
                MaxOffset = (
                    RenderMath.QuantizedScrollRange(rootContentSize.Width, viewport.Width, 1f),
                    RenderMath.QuantizedScrollRange(rootContentSize.Height, viewport.Height, 1f)),
            },
        ];

        // `Transforms` is accumulated top-down, so a non-translation matrix on the candidate
        // identifies either its own transform or an affine ancestor.
        bool[] affineCoordinateSpace = new bool[nodeCapacity];
        foreach (NodeId id in nodes)
        {
            if (id.Index < nodeCapacity)
            {
                affineCoordinateSpace[id.Index] =
                    Transforms.TryGetValue(id, out Affine2 transform) && !transform.IsTranslation();
            }
        }

        NodeId? root = null;
        foreach (NodeId id in nodes)
        {
            if (tree.GetNode(id)?.IsElement == true)
            {
                root = id;
                break;
            }
        }

        if (root is { } rootId)
        {
            AssignScrollOwners(
                tree,
                rootId,
                ScrollId.Root,
                viewportFixed,
                affineCoordinateSpace,
                containers,
                nodeContainer,
                movementOwner);
        }

        // Compute scrolling overflow for every boxed node in one reverse pass.
        Rect?[] overflowBounds = new Rect?[nodeCapacity];
        for (int index = nodes.Count - 1; index >= 0; index--)
        {
            NodeId id = nodes[index];
            if (!Rects.TryGetValue(id, out Rect rect))
            {
                continue;
            }

            Styles.TryGetValue(id, out LayoutStyle? style);
            Rect paddingRect = style is null
                ? rect
                : new Rect(
                    rect.X + style.Border.Left,
                    rect.Y + style.Border.Top,
                    F32.Max(rect.Width - style.Border.Left - style.Border.Right, 0f),
                    F32.Max(rect.Height - style.Border.Top - style.Border.Bottom, 0f));
            Rect visualPadding = Transforms.TryGetValue(id, out Affine2 ownTransform)
                ? ownTransform.MapRect(paddingRect)
                : paddingRect;
            Rect local = visualPadding;
            foreach (NodeId child in DomTraversal.RenderedChildren(tree, id))
            {
                if (child.Index >= nodeCapacity || overflowBounds[child.Index] is not { } childOverflow)
                {
                    continue;
                }

                Rect contribution = childOverflow;
                if (Styles.TryGetValue(child, out LayoutStyle? childStyle)
                    && childStyle.OverflowHidden
                    && !childStyle.OverflowPropagatedToViewport)
                {
                    Rect borderBox = childOverflow;
                    if (Rects.TryGetValue(child, out Rect childRect))
                    {
                        borderBox = Transforms.TryGetValue(child, out Affine2 childTransform)
                            ? childTransform.MapRect(childRect)
                            : childRect;
                    }

                    float x0 = childStyle.ClipsOverflowX() ? borderBox.X : childOverflow.X;
                    float x1 = childStyle.ClipsOverflowX()
                        ? borderBox.X + borderBox.Width
                        : childOverflow.X + childOverflow.Width;
                    float y0 = childStyle.ClipsOverflowY() ? borderBox.Y : childOverflow.Y;
                    float y1 = childStyle.ClipsOverflowY()
                        ? borderBox.Y + borderBox.Height
                        : childOverflow.Y + childOverflow.Height;
                    contribution = new Rect(x0, y0, F32.Max(x1 - x0, 0f), F32.Max(y1 - y0, 0f));
                }

                local = local.Union(contribution);
            }

            (float Width, float Height) content = (
                F32.Max(local.X + local.Width - visualPadding.X, visualPadding.Width),
                F32.Max(local.Y + local.Height - visualPadding.Y, visualPadding.Height));

            // Scroll containers include trailing end padding in their scrolling area.
            if (style is not null && style.OverflowScrollContainer)
            {
                if (content.Width > visualPadding.Width)
                {
                    content.Width += style.Padding.Right;
                }

                if (content.Height > visualPadding.Height)
                {
                    content.Height += style.Padding.Bottom;
                }
            }

            if (id.Index < nodeCapacity)
            {
                nodeContentSize[id.Index] = style is not null && style.IgnoresUsedBoxSizes()
                    ? (0f, 0f)
                    : content;
                overflowBounds[id.Index] = local;
            }
        }

        for (int index = 1; index < containers.Count; index++)
        {
            ScrollContainer container = containers[index];
            (float Width, float Height) contentSize = container.ClientSize;
            if (container.Node is { } node
                && node.Index < nodeCapacity
                && nodeContentSize[node.Index] is { } measured)
            {
                contentSize = measured;
            }

            containers[index] = container with
            {
                ContentSize = contentSize,
                MaxOffset = (
                    RenderMath.QuantizedScrollRange(contentSize.Width, container.ClientSize.Width, 1f),
                    RenderMath.QuantizedScrollRange(contentSize.Height, container.ClientSize.Height, 1f)),
            };
        }

        return new ScrollTree
        {
            Containers = containers,
            NodeContainer = nodeContainer,
            NodeContentSize = nodeContentSize,
            MovementOwner = movementOwner,
        };
    }

    private void AssignScrollOwners(
        DomTree tree,
        NodeId id,
        ScrollId? inheritedOwner,
        HashSet<NodeId> viewportFixed,
        bool[] affineCoordinateSpace,
        List<ScrollContainer> containers,
        ScrollId?[] nodeContainer,
        ScrollId?[] movementOwner)
    {
        bool isFixed = viewportFixed.Contains(id);
        bool parentFixed = DomTraversal.RenderedParent(tree, id) is { } parent
            && viewportFixed.Contains(parent);

        // Only the boundary that enters the viewport-fixed coordinate space drops root
        // movement. Descendants inherit that zero-based space.
        bool startsViewportFixed = isFixed && !parentFixed;
        ScrollId? owner = startsViewportFixed ? null : inheritedOwner;
        if (id.Index < movementOwner.Length)
        {
            movementOwner[id.Index] = owner;
        }

        Styles.TryGetValue(id, out LayoutStyle? style);
        Rect? rect = Rects.TryGetValue(id, out Rect found) ? found : null;
        bool establishes = style is not null
            && style.OverflowScrollContainer
            && !style.OverflowPropagatedToViewport
            && !style.DisplayContents
            && rect is not null
            && !(id.Index < affineCoordinateSpace.Length && affineCoordinateSpace[id.Index]);

        ScrollId? childOwner = owner;
        if (establishes && style is not null && rect is { } box)
        {
            (float Width, float Height) client = (
                F32.Max(box.Width - style.Border.Left - style.Border.Right, 0f),
                F32.Max(box.Height - style.Border.Top - style.Border.Bottom, 0f));
            ScrollId sid = new((uint)containers.Count);
            containers.Add(new ScrollContainer
            {
                Node = id,
                Parent = owner,
                ClientSize = client,
                ContentSize = client,
                MaxOffset = (0f, 0f),
            });
            if (id.Index < nodeContainer.Length)
            {
                nodeContainer[id.Index] = sid;
            }

            childOwner = sid;
        }

        foreach (NodeId child in DomTraversal.RenderedChildren(tree, id))
        {
            AssignScrollOwners(
                tree,
                child,
                childOwner,
                viewportFixed,
                affineCoordinateSpace,
                containers,
                nodeContainer,
                movementOwner);
        }
    }

    /// <summary>Root scrolling overflow in CSS pixels.</summary>
    public (float Width, float Height) ScrollingContentSize(
        DomTree tree,
        (float Width, float Height) viewport)
    {
        HashSet<NodeId> fixedNodes = ViewportFixedNodes(tree);
        return ScrollingContentSizeWithFixed(tree, viewport, fixedNodes);
    }

    internal (float Width, float Height) ScrollingContentSizeWithFixed(
        DomTree tree,
        (float Width, float Height) viewport,
        HashSet<NodeId> fixedNodes)
    {
        float right = F32.Max(viewport.Width, 0f);
        float bottom = F32.Max(viewport.Height, 0f);

        NodeId? root = null;
        foreach (NodeId id in tree.Descendants(tree.Document))
        {
            if (tree.GetNode(id)?.IsElement == true)
            {
                root = id;
                break;
            }
        }

        if (root is { } rootId)
        {
            AccumulateScrollingOverflow(tree, rootId, null, fixedNodes, ref right, ref bottom);
        }

        return (MathF.Ceiling(right), MathF.Ceiling(bottom));
    }

    private void AccumulateScrollingOverflow(
        DomTree tree,
        NodeId id,
        OverflowClip? inheritedClip,
        HashSet<NodeId> fixedNodes,
        ref float right,
        ref float bottom)
    {
        if (fixedNodes.Contains(id))
        {
            return;
        }

        if (Rects.TryGetValue(id, out Rect rect))
        {
            Rect overflow = Transforms.TryGetValue(id, out Affine2 transform)
                ? transform.MapRect(rect)
                : rect;
            Rect? visible = inheritedClip is null ? overflow : inheritedClip.IntersectRect(overflow);
            if (visible is { } bounds)
            {
                right = F32.Max(right, bounds.X + bounds.Width);
                bottom = F32.Max(bottom, bounds.Y + bounds.Height);
            }
        }

        // Overflow propagated from html/body establishes the viewport clip for painting, but
        // it does not truncate the root scrolling area's CSSOM overflow dimensions.
        OverflowClip? childClip = inheritedClip;
        if (Styles.TryGetValue(id, out LayoutStyle? style)
            && Rects.TryGetValue(id, out Rect ownRect)
            && style.OverflowHidden
            && !style.OverflowPropagatedToViewport)
        {
            (float tx, float ty) = Translates.TryGetValue(id, out var translate) ? translate : (0f, 0f);
            OverflowClip own = OverflowClip.ForBox(ownRect, style, tx, ty);
            childClip = inheritedClip is null ? own : inheritedClip.Intersect(own);
        }

        foreach (NodeId child in DomTraversal.RenderedChildren(tree, id))
        {
            AccumulateScrollingOverflow(tree, child, childClip, fixedNodes, ref right, ref bottom);
        }
    }

    /// <summary>
    /// Capture sticky constraints from the normal-flow result. The historical method name
    /// remains for API compatibility; returned frames include both the root viewport and
    /// element scrolling containers.
    /// </summary>
    public StickyLayout RootStickyLayout(DomTree tree, (float Width, float Height) viewport)
    {
        HashSet<NodeId> viewportFixed = ViewportFixedNodes(tree);
        (float Width, float Height) content = ScrollingContentSizeWithFixed(tree, viewport, viewportFixed);
        ScrollTree scrollTree = BuildScrollTree(tree, viewport, content, viewportFixed);
        StickyLayout sticky = StickyLayoutWithGeometry(tree, viewport, content, scrollTree);
        sticky.CompatibilityScrollTree = scrollTree;
        return sticky;
    }

    internal StickyLayout StickyLayoutWithGeometry(
        DomTree tree,
        (float Width, float Height) viewport,
        (float Width, float Height) content,
        ScrollTree scrollTree)
    {
        Rect rootContaining = new(0f, 0f, content.Width, content.Height);
        StickyLayout layout = new();
        Dictionary<NodeId, NodeId?> nearestSticky = [];
        Dictionary<NodeId, NodeId?> inheritedClipSticky = [];

        // Propagate the nearest authored scroll container once in rendered preorder. The
        // boolean distinguishes a supported ScrollTree owner from a real but affine/otherwise
        // unsupported scrolling coordinate space.
        (NodeId Node, bool Supported)?[] nearestScrollport =
            new (NodeId, bool)?[scrollTree.MovementOwner.Length];
        float rootFontSize = 16f;
        if (tree.QuerySelector("html") is { } htmlRoot
            && Styles.TryGetValue(htmlRoot, out LayoutStyle? htmlStyle)
            && htmlStyle.FontSize is { } htmlFontSize)
        {
            rootFontSize = htmlFontSize;
        }

        foreach (NodeId id in DomTraversal.RenderedDescendants(tree, tree.Document))
        {
            NodeId? parent = DomTraversal.RenderedParent(tree, id);
            (NodeId Node, bool Supported)? inheritedScrollport = null;
            if (parent is { } scrollParent && scrollParent.Index < nearestScrollport.Length)
            {
                inheritedScrollport = nearestScrollport[scrollParent.Index];
            }

            Styles.TryGetValue(id, out LayoutStyle? style);
            bool establishesAuthoredScrollport = style is not null
                && style.OverflowScrollContainer
                && !style.OverflowPropagatedToViewport
                && !style.DisplayContents
                && Rects.ContainsKey(id);
            (NodeId Node, bool Supported)? descendantsScrollport = establishesAuthoredScrollport
                ? (id, id.Index < scrollTree.NodeContainer.Length
                    && scrollTree.NodeContainer[id.Index] is not null)
                : inheritedScrollport;
            if (id.Index < nearestScrollport.Length)
            {
                nearestScrollport[id.Index] = descendantsScrollport;
            }

            NodeId? parentSticky = parent is { } stickyParent
                && nearestSticky.TryGetValue(stickyParent, out NodeId? found)
                    ? found
                    : null;
            NodeId? inheritedClip = null;
            if (parent is { } clipParent)
            {
                bool parentClips = Styles.TryGetValue(clipParent, out LayoutStyle? parentStyle)
                    && parentStyle.OverflowHidden;
                Dictionary<NodeId, NodeId?> source = parentClips ? nearestSticky : inheritedClipSticky;
                inheritedClip = source.TryGetValue(clipParent, out NodeId? owner) ? owner : null;
            }

            if (inheritedClip is { } clipOwner)
            {
                layout.ClipOwners[id] = clipOwner;
            }

            inheritedClipSticky[id] = inheritedClip;

            ScrollId? scrollOwnerSlot = id.Index < scrollTree.MovementOwner.Length
                ? scrollTree.MovementOwner[id.Index]
                : null;
            if (scrollOwnerSlot is not { } scrollOwner)
            {
                nearestSticky[id] = null;
                continue;
            }

            ScrollContainer container = scrollTree.Containers[scrollOwner.Index];
            NodeId? scrollportNode = container.Node;

            // ScrollTree conservatively declines affine scrolling coordinate spaces. Preserve
            // that fallback for sticky too.
            bool supportedScrollOwner = inheritedScrollport switch
            {
                { Supported: true } authored => scrollportNode == authored.Node,
                { Supported: false } => false,
                _ => scrollportNode is null,
            };

            // General affine sticky constraints require solving in the transformed scrollport
            // coordinate space. Until that solver is present, decline sticky below an affine
            // ancestor instead of returning geometry that disagrees with paint.
            bool supportedCoordinateSpace = parent is not { } transformParent
                || !Transforms.TryGetValue(transformParent, out Affine2 parentTransform)
                || parentTransform.IsTranslation();

            bool anyInset = false;
            if (style is not null)
            {
                foreach (Dimension? inset in style.Inset)
                {
                    if (inset is not null)
                    {
                        anyInset = true;
                        break;
                    }
                }
            }

            bool isSticky = style is not null
                && style.PositionSticky
                && anyInset
                && supportedScrollOwner
                && supportedCoordinateSpace;
            if (!isSticky)
            {
                nearestSticky[id] = parentSticky;
                if (parentSticky is { } inheritedOwner)
                {
                    layout.Owners[id] = inheritedOwner;
                }

                continue;
            }

            if (style is null || !Rects.TryGetValue(id, out Rect rect))
            {
                nearestSticky[id] = parentSticky;
                continue;
            }

            (float tx, float ty) = Translates.TryGetValue(id, out var ownTranslate) ? ownTranslate : (0f, 0f);

            // Sticky constraints are solved from the box's normal-flow position, before its
            // own transform is painted.
            (float ownTx, float ownTy) = DomTransforms.ResolvedOwnTranslate(style, rect, 16f, viewport);
            Rect normal = rect with { X = rect.X + tx - ownTx, Y = rect.Y + ty - ownTy };

            Rect? containing = null;
            NodeId? containingNode = null;
            NodeId? ancestor = parent;
            while (ancestor is { } candidate)
            {
                if (Styles.TryGetValue(candidate, out LayoutStyle? candidateStyle)
                    && Rects.TryGetValue(candidate, out Rect candidateRect)
                    && candidateStyle.Display != Display.Inline
                    && !candidateStyle.DisplayContents)
                {
                    (float ctx, float cty) = Translates.TryGetValue(candidate, out var candidateTranslate)
                        ? candidateTranslate
                        : (0f, 0f);
                    containing = new Rect(
                        candidateRect.X + ctx + candidateStyle.Border.Left + candidateStyle.Padding.Left,
                        candidateRect.Y + cty + candidateStyle.Border.Top + candidateStyle.Padding.Top,
                        F32.Max(
                            candidateRect.Width
                            - candidateStyle.Border.Left
                            - candidateStyle.Border.Right
                            - candidateStyle.Padding.Left
                            - candidateStyle.Padding.Right,
                            0f),
                        F32.Max(
                            candidateRect.Height
                            - candidateStyle.Border.Top
                            - candidateStyle.Border.Bottom
                            - candidateStyle.Padding.Top
                            - candidateStyle.Padding.Bottom,
                            0f));
                    containingNode = candidate;
                    break;
                }

                ancestor = DomTraversal.RenderedParent(tree, candidate);
            }

            Rect scrollport = new(0f, 0f, viewport.Width, viewport.Height);
            if (scrollportNode is { } portNode
                && Styles.TryGetValue(portNode, out LayoutStyle? portStyle)
                && Rects.TryGetValue(portNode, out Rect portRect))
            {
                (float ptx, float pty) = Translates.TryGetValue(portNode, out var portTranslate)
                    ? portTranslate
                    : (0f, 0f);
                scrollport = new Rect(
                    portRect.X + ptx + portStyle.Border.Left + portStyle.Padding.Left,
                    portRect.Y + pty + portStyle.Border.Top + portStyle.Padding.Top,
                    F32.Max(
                        portRect.Width
                        - portStyle.Border.Left
                        - portStyle.Border.Right
                        - portStyle.Padding.Left
                        - portStyle.Padding.Right,
                        0f),
                    F32.Max(
                        portRect.Height
                        - portStyle.Border.Top
                        - portStyle.Border.Bottom
                        - portStyle.Padding.Top
                        - portStyle.Padding.Bottom,
                        0f));
            }

            layout.Frames.Add(new StickyFrame
            {
                Id = id,
                ParentSticky = parentSticky,
                ScrollOwner = scrollOwner,
                ScrollportNode = scrollportNode,
                Scrollport = scrollport,
                Normal = normal,
                Containing = containing ?? rootContaining,
                ContainingIsScrollport = containingNode == scrollportNode,
                Margin = style.Margin,
                Inset = [.. style.Inset],
                InsetExpressions = [.. style.InsetExpressions],
                FontSize = style.FontSize ?? 16f,
                RootFontSize = rootFontSize,
                RtlInline = style.Direction == Layout.Direction.Rtl,
            });
            layout.Owners[id] = id;
            nearestSticky[id] = id;
        }

        return layout;
    }
}

/// <summary>
/// Prepared geometry shared by CSSOM, scrolling, sticky positioning, and paint.
/// </summary>
internal sealed class DerivedLayoutState
{
    internal required (float Width, float Height) ContentSize { get; init; }

    internal required HashSet<NodeId> ViewportFixed { get; init; }

    internal required StickyLayout Sticky { get; init; }

    internal required ScrollTree ScrollTree { get; init; }
}

internal sealed class DerivedGeometryState
{
    internal required (float Width, float Height) ContentSize { get; init; }

    internal required StickyLayout Sticky { get; init; }

    internal required ScrollTree ScrollTree { get; init; }
}
