using System.Text;

namespace Obscura.Render.Css;

/// <summary>
/// Selector-source analysis used by the invalidation map and the nesting
/// flattener. These walk selector text directly rather than a compiled
/// selector, so they stay independent of the selector engine.
/// </summary>
internal static class CssSelectorText
{
    /// <summary>
    /// Consume one CSS identifier starting at <paramref name="index"/>,
    /// decoding hex and literal escapes. Returns the decoded value and the
    /// index just past it.
    /// </summary>
    public static (string Value, int Next) ConsumeIdentifier(ReadOnlySpan<char> chars, int index)
    {
        var value = new StringBuilder();
        while (index < chars.Length)
        {
            var current = chars[index];
            if (current == '\\')
            {
                index += 1;
                if (index >= chars.Length)
                {
                    break;
                }

                var escaped = chars[index];
                if (CssText.IsAsciiHexDigit(escaped))
                {
                    var start = index;
                    while (index < chars.Length && index - start < 6 && CssText.IsAsciiHexDigit(chars[index]))
                    {
                        index++;
                    }

                    var codepoint = 0u;
                    for (var digit = start; digit < index; digit++)
                    {
                        codepoint = (codepoint * 16) + HexValue(chars[digit]);
                    }

                    value.Append(
                        codepoint is > 0 and <= 0x10FFFF and not (>= 0xD800 and <= 0xDFFF)
                            ? char.ConvertFromUtf32((int)codepoint)
                            : "�");

                    if (index < chars.Length && CssText.IsWhitespace(chars[index]))
                    {
                        index++;
                    }

                    continue;
                }

                value.Append(escaped);
                index++;
                continue;
            }

            if (CssText.IsAlphanumeric(current) || current is '_' or '-' || !CssText.IsAscii(current))
            {
                value.Append(current);
                index++;
            }
            else
            {
                break;
            }
        }

        return (value.ToString(), index);
    }

    private static uint HexValue(char digit) => digit switch
    {
        >= '0' and <= '9' => (uint)(digit - '0'),
        >= 'a' and <= 'f' => (uint)(digit - 'a' + 10),
        _ => (uint)(digit - 'A' + 10),
    };

    /// <summary>
    /// Index of the delimiter closing the one at <paramref name="open"/>,
    /// skipping escapes and quoted strings.
    /// </summary>
    public static int? MatchingDelimiter(ReadOnlySpan<char> chars, int open, char opening, char closing)
    {
        var depth = 1;
        char? quote = null;
        var index = open + 1;
        while (index < chars.Length)
        {
            var current = chars[index];
            if (current == '\\')
            {
                index = Math.Min(index + 2, chars.Length);
                continue;
            }

            if (quote is { } active)
            {
                if (current == active)
                {
                    quote = null;
                }

                index++;
                continue;
            }

            if (current is '\'' or '"')
            {
                quote = current;
            }
            else if (current == opening)
            {
                depth++;
            }
            else if (current == closing)
            {
                depth--;
                if (depth == 0)
                {
                    return index;
                }
            }

            index++;
        }

        return null;
    }

    /// <summary>
    /// Split one complex selector into compounds and the traversal generated by
    /// a dependency in each compound. Whitespace surrounding an explicit
    /// combinator is not misread as an extra descendant combinator.
    /// </summary>
    public static (List<(string Compound, InvalidationReaches Reaches)> Compounds, bool Malformed)
        InvalidationCompounds(string selector)
    {
        var chars = selector.AsSpan();
        var compounds = new List<(string Compound, InvalidationReaches Reaches)>();
        var start = 0;
        var index = 0;
        var parenDepth = 0;
        var bracketDepth = 0;
        char? quote = null;
        var malformed = false;

        bool Push(int compoundStart, int end, InvalidationReaches reaches)
        {
            var compound = selector[compoundStart..end].Trim();
            if (compound.Length != 0)
            {
                compounds.Add((compound, reaches));
                return true;
            }

            return false;
        }

        while (index < chars.Length)
        {
            var current = chars[index];
            if (current == '\\')
            {
                index = Math.Min(index + 2, chars.Length);
                continue;
            }

            if (quote is { } active)
            {
                if (current == active)
                {
                    quote = null;
                }

                index++;
                continue;
            }

            if (current is '\'' or '"')
            {
                quote = current;
                index++;
                continue;
            }

            switch (current)
            {
                case '(':
                    parenDepth++;
                    break;
                case ')':
                    if (parenDepth == 0)
                    {
                        malformed = true;
                    }
                    else
                    {
                        parenDepth--;
                    }

                    break;
                case '[':
                    bracketDepth++;
                    break;
                case ']':
                    if (bracketDepth == 0)
                    {
                        malformed = true;
                    }
                    else
                    {
                        bracketDepth--;
                    }

                    break;
                case '>' or '+' or '~' when parenDepth == 0 && bracketDepth == 0:
                {
                    var reaches = current == '>'
                        ? InvalidationReaches.Descendants
                        : InvalidationReaches.Siblings;
                    if (!Push(start, index, reaches))
                    {
                        malformed = true;
                    }

                    index++;
                    while (index < chars.Length && CssText.IsWhitespace(chars[index]))
                    {
                        index++;
                    }

                    start = index;
                    continue;
                }

                case ',' when parenDepth == 0 && bracketDepth == 0:
                    malformed = true;
                    break;
                default:
                    if (CssText.IsWhitespace(current) && parenDepth == 0 && bracketDepth == 0)
                    {
                        var whitespace = index;
                        while (index < chars.Length && CssText.IsWhitespace(chars[index]))
                        {
                            index++;
                        }

                        if (index < chars.Length && chars[index] is '>' or '+' or '~')
                        {
                            continue;
                        }

                        if (index < chars.Length)
                        {
                            if (!Push(start, whitespace, InvalidationReaches.Descendants))
                            {
                                malformed = true;
                            }

                            start = index;
                            continue;
                        }

                        goto done;
                    }

                    break;
            }

            index++;
        }

    done:
        if (parenDepth != 0 || bracketDepth != 0 || quote is not null)
        {
            malformed = true;
        }

        var tail = selector[start..].Trim();
        if (tail.Length != 0)
        {
            compounds.Add((tail, InvalidationReaches.Self));
        }
        else if (compounds.Count == 0)
        {
            malformed = true;
        }

        var descendantsToRight = false;
        for (var position = compounds.Count - 1; position >= 0; position--)
        {
            var (compound, reaches) = compounds[position];
            if (reaches.Contains(InvalidationReaches.Descendants))
            {
                descendantsToRight = true;
            }
            else if (descendantsToRight && reaches.Contains(InvalidationReaches.Siblings))
            {
                // `.foo ~ .bar .child`: a change to `.foo` can affect
                // descendants of following siblings. A flat Siblings reach is
                // insufficient unless phase 2 also carries the remaining
                // descendant path.
                compounds[position] = (compound, reaches.Union(InvalidationReaches.Conservative));
            }
        }

        return (compounds, malformed);
    }

    /// <summary>The selector after the <c>of</c> keyword in an <c>:nth-child()</c> argument.</summary>
    public static string? NthOfSelector(string arguments)
    {
        var chars = arguments.AsSpan();
        var bracketDepth = 0;
        var parenDepth = 0;
        char? quote = null;
        var index = 0;
        while (index + 1 < chars.Length)
        {
            var current = chars[index];
            if (current == '\\')
            {
                index += 2;
                continue;
            }

            if (quote is { } active)
            {
                if (current == active)
                {
                    quote = null;
                }

                index++;
                continue;
            }

            switch (current)
            {
                case '\'':
                case '"':
                    quote = current;
                    break;
                case '[':
                    bracketDepth++;
                    break;
                case ']':
                    bracketDepth = Math.Max(bracketDepth - 1, 0);
                    break;
                case '(':
                    parenDepth++;
                    break;
                case ')':
                    parenDepth = Math.Max(parenDepth - 1, 0);
                    break;
            }

            if (bracketDepth == 0
                && parenDepth == 0
                && (index == 0 || CssText.IsWhitespace(chars[index - 1]))
                && CssText.AsciiLower(current) == 'o'
                && CssText.AsciiLower(chars[index + 1]) == 'f'
                && (index + 2 >= chars.Length || CssText.IsWhitespace(chars[index + 2])))
            {
                var tail = index + 2 >= arguments.Length ? string.Empty : arguments[(index + 2)..];
                return tail.Trim();
            }

            index++;
        }

        return null;
    }

    /// <summary>The lowercased local name a compound requires, when it has one.</summary>
    public static string? CompoundLocalName(string compound)
    {
        var trimmed = compound.Trim();
        var chars = trimmed.AsSpan();
        int index;
        if (chars.Length > 0 && chars[0] == '|')
        {
            index = 1;
        }
        else if (chars.Length > 0 && chars[0] == '*')
        {
            if (chars.Length < 2 || chars[1] != '|')
            {
                return null;
            }

            index = 2;
        }
        else
        {
            var (first, end) = ConsumeIdentifier(chars, 0);
            if (first.Length == 0)
            {
                return null;
            }

            if (end >= chars.Length || chars[end] != '|')
            {
                return CssText.AsciiLower(first);
            }

            index = end + 1;
        }

        if (index < chars.Length && chars[index] == '*')
        {
            return null;
        }

        var (local, _) = ConsumeIdentifier(chars, index);
        return local.Length != 0 ? CssText.AsciiLower(local) : null;
    }

    /// <summary>
    /// Whether the relative selector's subject compound has a positive key which
    /// an inserted/removed subtree can look up. Keys hidden only inside
    /// <c>:is()</c> or negation are deliberately not credited; treating those as
    /// unkeyed costs a broader invalidation but cannot miss an activation.
    /// </summary>
    public static bool RelativeSelectorSubjectHasKey(string selector)
    {
        selector = selector.Trim();
        if (selector.Length != 0 && selector[0] is '>' or '+' or '~')
        {
            selector = selector[1..].TrimStart();
        }

        var (compounds, malformed) = InvalidationCompounds(selector);
        if (malformed || compounds.Count == 0)
        {
            return false;
        }

        var subject = compounds[^1].Compound;
        if (CompoundLocalName(subject) is not null)
        {
            return true;
        }

        var chars = subject.AsSpan();
        var parenDepth = 0;
        var bracketDepth = 0;
        char? quote = null;
        var index = 0;
        while (index < chars.Length)
        {
            var current = chars[index];
            if (current == '\\')
            {
                index = Math.Min(index + 2, chars.Length);
                continue;
            }

            if (quote is { } active)
            {
                if (current == active)
                {
                    quote = null;
                }

                index++;
                continue;
            }

            if (current is '\'' or '"')
            {
                quote = current;
            }
            else if (current == ':' && parenDepth == 0 && bracketDepth == 0)
            {
                var (name, next) = ConsumeIdentifier(chars, index + 1);
                var lower = CssText.AsciiLower(name);
                if (lower is "is" or "where" && next < chars.Length && chars[next] == '(')
                {
                    if (MatchingDelimiter(chars, next, '(', ')') is not { } close)
                    {
                        return false;
                    }

                    var arguments = subject[(next + 1)..close];
                    var alternatives = SplitSelectorList(arguments);
                    if (alternatives.Count != 0
                        && alternatives.All(alternative => RelativeSelectorSubjectHasKey(alternative.Trim())))
                    {
                        return true;
                    }

                    index = close + 1;
                    continue;
                }
            }
            else if (current == '(')
            {
                parenDepth++;
            }
            else if (current == ')')
            {
                parenDepth = Math.Max(parenDepth - 1, 0);
            }
            else if (current == '[' && parenDepth == 0)
            {
                if (bracketDepth == 0)
                {
                    return true;
                }

                bracketDepth++;
            }
            else if (current == ']' && parenDepth == 0)
            {
                bracketDepth = Math.Max(bracketDepth - 1, 0);
            }
            else if (parenDepth == 0 && bracketDepth == 0 && current is '#' or '.')
            {
                return true;
            }

            index++;
        }

        return false;
    }

    /// <summary>
    /// Pick one positive key which every match of this exact anchor compound
    /// must have. Functional pseudos are skipped as opaque boolean expressions;
    /// using a key from one <c>:is()</c> arm as a mandatory filter would be
    /// unsound.
    /// </summary>
    public static RelationalSelectorKey? RelationalAnchorKey(string compound)
    {
        if (CompoundLocalName(compound) is { } localName)
        {
            return RelationalSelectorKey.LocalName(localName);
        }

        var chars = compound.AsSpan();
        var index = 0;
        while (index < chars.Length)
        {
            switch (chars[index])
            {
                case '#':
                {
                    var (id, next) = ConsumeIdentifier(chars, index + 1);
                    if (id.Length != 0)
                    {
                        return RelationalSelectorKey.Id(id);
                    }

                    index = Math.Max(next, index + 1);
                    break;
                }

                case '.':
                {
                    var (className, next) = ConsumeIdentifier(chars, index + 1);
                    if (className.Length != 0)
                    {
                        return RelationalSelectorKey.Class(className);
                    }

                    index = Math.Max(next, index + 1);
                    break;
                }

                case '[':
                {
                    if (MatchingDelimiter(chars, index, '[', ']') is not { } close)
                    {
                        return null;
                    }

                    var nameIndex = index + 1;
                    while (nameIndex < chars.Length && CssText.IsWhitespace(chars[nameIndex]))
                    {
                        nameIndex++;
                    }

                    // Attribute lookup is the unqualified HTML lookup. A
                    // namespace-qualified selector cannot use that as a
                    // mandatory anchor filter without risking a false rejection.
                    if (nameIndex < chars.Length && chars[nameIndex] is '*' or '|')
                    {
                        index = close + 1;
                        continue;
                    }

                    var (attribute, end) = ConsumeIdentifier(chars, nameIndex);
                    if (end < chars.Length && chars[end] == '|')
                    {
                        index = close + 1;
                        continue;
                    }

                    if (attribute.Length != 0 && end <= close)
                    {
                        return RelationalSelectorKey.Attribute(CssText.AsciiLower(attribute));
                    }

                    index = close + 1;
                    break;
                }

                case ':':
                {
                    var pseudoStart = index + (index + 1 < chars.Length && chars[index + 1] == ':' ? 1 : 0) + 1;
                    var (_, next) = ConsumeIdentifier(chars, pseudoStart);
                    if (next < chars.Length && chars[next] == '(')
                    {
                        if (MatchingDelimiter(chars, next, '(', ')') is not { } close)
                        {
                            return null;
                        }

                        index = close + 1;
                    }
                    else
                    {
                        index = Math.Max(next, index + 1);
                    }

                    break;
                }

                case '\\':
                    index = Math.Min(index + 2, chars.Length);
                    break;
                default:
                    index++;
                    break;
            }
        }

        return null;
    }

    private static void PushRelationalSelectorKey(List<RelationalSelectorKey> keys, RelationalSelectorKey key)
    {
        if (!keys.Contains(key))
        {
            keys.Add(key);
        }
    }

    /// <summary>
    /// Collect cheap positive keys anywhere along a relative-selector path. A
    /// child-list insertion which contains none of these keys cannot make the
    /// path start matching. This is an early rejection only: each key is treated
    /// as an alternative trigger, so compounds requiring several keys remain
    /// sound.
    /// </summary>
    public static void CollectRelationalSelectorKeys(string selector, List<RelationalSelectorKey> keys)
    {
        selector = selector.Trim();
        if (selector.Length != 0 && selector[0] is '>' or '+' or '~')
        {
            selector = selector[1..].TrimStart();
        }

        var (compounds, _) = InvalidationCompounds(selector);
        foreach (var (compound, _) in compounds)
        {
            CollectRelationalCompoundKeys(compound, keys);
        }
    }

    public static void CollectRelationalCompoundKeys(string compound, List<RelationalSelectorKey> keys)
    {
        if (CompoundLocalName(compound) is { } localName)
        {
            PushRelationalSelectorKey(keys, RelationalSelectorKey.LocalName(localName));
        }

        var chars = compound.AsSpan();
        var index = 0;
        while (index < chars.Length)
        {
            switch (chars[index])
            {
                case '#':
                {
                    var (id, next) = ConsumeIdentifier(chars, index + 1);
                    if (id.Length != 0)
                    {
                        PushRelationalSelectorKey(keys, RelationalSelectorKey.Id(id));
                    }

                    index = Math.Max(next, index + 1);
                    break;
                }

                case '.':
                {
                    var (className, next) = ConsumeIdentifier(chars, index + 1);
                    if (className.Length != 0)
                    {
                        PushRelationalSelectorKey(keys, RelationalSelectorKey.Class(className));
                    }

                    index = Math.Max(next, index + 1);
                    break;
                }

                case '[':
                {
                    if (MatchingDelimiter(chars, index, '[', ']') is not { } close)
                    {
                        return;
                    }

                    var nameIndex = index + 1;
                    while (nameIndex < chars.Length && CssText.IsWhitespace(chars[nameIndex]))
                    {
                        nameIndex++;
                    }

                    string first;
                    int firstEnd;
                    if (nameIndex < chars.Length && chars[nameIndex] == '*')
                    {
                        first = string.Empty;
                        firstEnd = nameIndex + 1;
                    }
                    else
                    {
                        (first, firstEnd) = ConsumeIdentifier(chars, nameIndex);
                    }

                    string attribute;
                    int end;
                    if (firstEnd < chars.Length && chars[firstEnd] == '|')
                    {
                        (attribute, end) = ConsumeIdentifier(chars, firstEnd + 1);
                    }
                    else
                    {
                        (attribute, end) = (first, firstEnd);
                    }

                    if (attribute.Length != 0 && end <= close)
                    {
                        PushRelationalSelectorKey(
                            keys,
                            RelationalSelectorKey.Attribute(CssText.AsciiLower(attribute)));
                    }

                    index = close + 1;
                    break;
                }

                case ':':
                {
                    var pseudoStart = index + (index + 1 < chars.Length && chars[index + 1] == ':' ? 1 : 0) + 1;
                    var (name, next) = ConsumeIdentifier(chars, pseudoStart);
                    if (next >= chars.Length || chars[next] != '(')
                    {
                        index = Math.Max(next, index + 1);
                        continue;
                    }

                    if (MatchingDelimiter(chars, next, '(', ')') is not { } close)
                    {
                        return;
                    }

                    var arguments = compound[(next + 1)..close];
                    switch (CssText.AsciiLower(name))
                    {
                        case "is":
                        case "where":
                        case "not":
                        case "has":
                            foreach (var alternative in SplitSelectorList(arguments))
                            {
                                CollectRelationalSelectorKeys(alternative.Trim(), keys);
                            }

                            break;
                        case "nth-child":
                        case "nth-last-child":
                        case "nth-of-type":
                        case "nth-last-of-type":
                            if (NthOfSelector(arguments) is { } ofSelector)
                            {
                                foreach (var alternative in SplitSelectorList(ofSelector))
                                {
                                    CollectRelationalSelectorKeys(alternative.Trim(), keys);
                                }
                            }

                            break;
                    }

                    index = close + 1;
                    break;
                }

                case '\\':
                    index = Math.Min(index + 2, chars.Length);
                    break;
                default:
                    index++;
                    break;
            }
        }
    }

    public static bool SelectorContainsPseudo(string selector, params string[] names)
    {
        var chars = selector.AsSpan();
        var index = 0;
        char? quote = null;
        var bracketDepth = 0;
        while (index < chars.Length)
        {
            var current = chars[index];
            if (current == '\\')
            {
                index = Math.Min(index + 2, chars.Length);
                continue;
            }

            if (quote is { } active)
            {
                if (current == active)
                {
                    quote = null;
                }

                index++;
                continue;
            }

            switch (current)
            {
                case '\'':
                case '"':
                    quote = current;
                    break;
                case '[':
                    bracketDepth++;
                    break;
                case ']':
                    bracketDepth = Math.Max(bracketDepth - 1, 0);
                    break;
                case ':' when bracketDepth == 0 && (index + 1 >= chars.Length || chars[index + 1] != ':'):
                {
                    var (name, next) = ConsumeIdentifier(chars, index + 1);
                    foreach (var expected in names)
                    {
                        if (CssText.EqualsAscii(name, expected))
                        {
                            return true;
                        }
                    }

                    index = Math.Max(next, index + 1);
                    continue;
                }
            }

            index++;
        }

        return false;
    }

    public static bool SelectorContainsAdjacentCombinator(string selector)
    {
        var chars = selector.AsSpan();
        var index = 0;
        char? quote = null;
        var bracketDepth = 0;
        while (index < chars.Length)
        {
            var current = chars[index];
            if (current == '\\')
            {
                index = Math.Min(index + 2, chars.Length);
                continue;
            }

            if (quote is { } active)
            {
                if (current == active)
                {
                    quote = null;
                }

                index++;
                continue;
            }

            switch (current)
            {
                case '\'':
                case '"':
                    quote = current;
                    break;
                case '[':
                    bracketDepth++;
                    break;
                case ']':
                    bracketDepth = Math.Max(bracketDepth - 1, 0);
                    break;
                case '+' when bracketDepth == 0:
                    return true;
            }

            index++;
        }

        return false;
    }

    /// <summary>
    /// Sibling combinators which participate in the current selector path.
    /// </summary>
    /// <remarks>
    /// Parentheses are deliberately skipped here. <c>:is()</c>/<c>:where()</c>/
    /// <c>:not()</c> alternatives are fed back through dependency collection
    /// separately, while <c>:has()</c> owns an upward invalidation path and must
    /// not poison ordinary sibling invalidation outside its anchor.
    /// </remarks>
    public static (bool Adjacent, bool General) SelectorSiblingCombinators(string selector)
    {
        var chars = selector.AsSpan();
        var index = 0;
        char? quote = null;
        var bracketDepth = 0;
        var parenDepth = 0;
        var adjacent = false;
        var general = false;
        while (index < chars.Length)
        {
            var current = chars[index];
            if (current == '\\')
            {
                index = Math.Min(index + 2, chars.Length);
                continue;
            }

            if (quote is { } active)
            {
                if (current == active)
                {
                    quote = null;
                }

                index++;
                continue;
            }

            switch (current)
            {
                case '\'':
                case '"':
                    quote = current;
                    break;
                case '[':
                    bracketDepth++;
                    break;
                case ']':
                    bracketDepth = Math.Max(bracketDepth - 1, 0);
                    break;
                case '(' when bracketDepth == 0:
                    parenDepth++;
                    break;
                case ')' when bracketDepth == 0:
                    parenDepth = Math.Max(parenDepth - 1, 0);
                    break;
                case '+' when bracketDepth == 0 && parenDepth == 0:
                    adjacent = true;
                    break;
                case '~' when bracketDepth == 0 && parenDepth == 0:
                    general = true;
                    break;
            }

            index++;
        }

        return (adjacent, general);
    }

    public static bool SelectorRequiresConservativeTracking(string selector)
    {
        var lower = CssText.AsciiLower(selector);
        return lower.Contains(":has(", StringComparison.Ordinal)
            || lower.Contains(":dir(", StringComparison.Ordinal)
            || lower.Contains(":lang(", StringComparison.Ordinal)
            || lower.Contains(":nth-child(", StringComparison.Ordinal)
            || lower.Contains(":nth-last-child(", StringComparison.Ordinal)
            || lower.Contains(":nth-of-type(", StringComparison.Ordinal)
            || lower.Contains(":nth-last-of-type(", StringComparison.Ordinal)
            || lower.Contains(":target", StringComparison.Ordinal);
    }

    /// <summary>
    /// Split a CSS selector list at top-level commas only, leaving commas inside
    /// <c>()</c> (<c>:is(a, b)</c>), <c>[]</c> (<c>[attr="a,b"]</c>) and quoted
    /// strings intact. A naive split shatters those grouped selectors into
    /// fragments that fail to compile, dropping the whole rule.
    /// </summary>
    public static List<string> SplitSelectorList(string selector)
    {
        var output = new List<string>();
        var parenDepth = 0;
        var bracketDepth = 0;
        char? quote = null;
        var current = new StringBuilder();
        var index = 0;
        while (index < selector.Length)
        {
            var character = selector[index];
            index++;
            if (character == '\\')
            {
                current.Append(character);
                if (index < selector.Length)
                {
                    current.Append(selector[index]);
                    index++;
                }

                continue;
            }

            if (quote == character)
            {
                quote = null;
                current.Append(character);
                continue;
            }

            if (character is '"' or '\'' && quote is null)
            {
                quote = character;
                current.Append(character);
                continue;
            }

            if (quote is null)
            {
                switch (character)
                {
                    case '(':
                        parenDepth++;
                        current.Append(character);
                        continue;
                    case ')':
                        parenDepth--;
                        current.Append(character);
                        continue;
                    case '[':
                        bracketDepth++;
                        current.Append(character);
                        continue;
                    case ']':
                        bracketDepth--;
                        current.Append(character);
                        continue;
                    case ',' when parenDepth == 0 && bracketDepth == 0:
                        output.Add(current.ToString());
                        current.Clear();
                        continue;
                }
            }

            current.Append(character);
        }

        output.Add(current.ToString());
        return output;
    }

    /// <summary>
    /// Combine a nested selector <paramref name="child"/> with its enclosing
    /// <paramref name="parent"/> (CSS Nesting). <c>&amp;</c> in the child is
    /// replaced by the parent; a child with no <c>&amp;</c> becomes a descendant.
    /// Both may be comma lists, so the result is the cartesian product.
    /// </summary>
    public static string CombineSelectors(string parent, string child)
    {
        var parentParts = SplitSelectorList(parent);
        var childParts = SplitSelectorList(child);
        var output = new List<string>();
        foreach (var rawChild in childParts)
        {
            var trimmedChild = rawChild.Trim();
            if (trimmedChild.Length == 0)
            {
                continue;
            }

            foreach (var rawParent in parentParts)
            {
                var trimmedParent = rawParent.Trim();
                output.Add(trimmedChild.Contains('&', StringComparison.Ordinal)
                    ? trimmedChild.Replace("&", trimmedParent, StringComparison.Ordinal)
                    : $"{trimmedParent} {trimmedChild}");
            }
        }

        return string.Join(", ", output);
    }

    /// <summary>
    /// If <paramref name="selector"/>'s rightmost compound is the pseudo-element
    /// <paramref name="which"/> (matching either the modern <c>::</c> or legacy
    /// <c>:</c> form), return everything before it, trimmed. Only a trailing
    /// pseudo-element is handled.
    /// </summary>
    public static string? StripPseudoElement(string selector, string which)
    {
        foreach (var prefix in (string[])["::", ":"])
        {
            var suffix = prefix + which;
            if (selector.EndsWith(suffix, StringComparison.Ordinal))
            {
                var baseSelector = selector[..^suffix.Length];
                if (baseSelector.Length != 0)
                {
                    return baseSelector.Trim();
                }
            }
        }

        return null;
    }
}
