// Port of vendor/taffy/src/compute/grid/explicit_grid.rs
//
// Helper functions for initialising GridTracks from styles. This mainly consists
// of evaluating grid-auto-* tracks and expanding repeat() definitions.
namespace Obscura.Render.Layout;

/// <summary>The auto-repeat fit strategy to use.</summary>
internal enum AutoRepeatStrategy : byte
{
    /// <summary>
    /// If the grid container has a definite size or max size in the relevant axis, the number of
    /// repetitions is the largest positive integer that does not overflow the content box.
    /// </summary>
    MaxRepetitionsThatDoNotOverflow,

    /// <summary>
    /// Otherwise, if the grid container has a definite min size in the relevant axis, the number of
    /// repetitions is the smallest positive integer that fulfills that minimum.
    /// </summary>
    MinRepetitionsThatDoOverflow,
}

/// <summary>Explicit grid sizing and grid track initialisation.</summary>
internal static class ExplicitGrid
{
    /// <summary>Compute the number of rows and columns in the explicit grid.</summary>
    /// <returns>The auto-repetition count and the total explicit track count.</returns>
    public static (ushort AutoRepetitions, ushort TrackCount) ComputeExplicitGridSizeInAxis(
        IGridContainerStyle style,
        float? autoFitContainerSize,
        AutoRepeatStrategy autoFitStrategy,
        CalcResolver resolveCalcValue,
        AbsoluteAxis axis)
    {
        var template = axis == AbsoluteAxis.Horizontal ? style.GridTemplateColumns : style.GridTemplateRows;
        if (template is null)
        {
            return (0, 0);
        }

        // If template contains no tracks, then there are trivially zero explicit tracks
        int trackCount = template.Count;
        if (trackCount == 0)
        {
            return (0, 0);
        }

        // If there are any repetitions that contain no tracks, then the whole definition should be
        // considered invalid and we default to no explicit tracks.
        foreach (var trackDef in template)
        {
            if (trackDef.Kind == GridTemplateComponentKind.Repeat && trackDef.Repetition!.TrackCount() == 0)
            {
                return (0, 0);
            }
        }

        // Compute the number of tracks generated by single track definitions and repetitions with a
        // fixed repetition count.
        ushort nonAutoRepeatingTrackCount = 0;
        foreach (var trackDef in template)
        {
            nonAutoRepeatingTrackCount += NonAutoRepeatingTracks(trackDef);
        }

        ushort autoRepetitionCount = 0;
        foreach (var trackDef in template)
        {
            if (trackDef.IsAutoRepetition())
            {
                autoRepetitionCount++;
            }
        }

        bool allTrackDefsHaveFixedComponent = true;
        foreach (var trackDef in template)
        {
            if (trackDef.Kind == GridTemplateComponentKind.Single)
            {
                allTrackDefsHaveFixedComponent &= trackDef.Single.HasFixedComponent();
            }
            else
            {
                foreach (var sizingFunction in trackDef.Repetition!.Tracks)
                {
                    allTrackDefsHaveFixedComponent &= sizingFunction.HasFixedComponent();
                }
            }
        }

        bool templateIsValid =
            autoRepetitionCount == 0 || (autoRepetitionCount == 1 && allTrackDefsHaveFixedComponent);

        // If the template is invalid because it contains multiple auto-repetition definitions or it
        // combines an auto-repetition with non-fixed-size track sizing functions, disregard it
        // entirely and default to zero explicit tracks.
        if (!templateIsValid)
        {
            return (0, 0);
        }

        // If there are no repetitions, the number of explicit tracks is simply the length of the
        // track definition list.
        if (autoRepetitionCount == 0)
        {
            return (0, nonAutoRepeatingTrackCount);
        }

        GridTemplateRepetition? repetitionDefinition = null;
        foreach (var def in template)
        {
            if (def.Kind == GridTemplateComponentKind.Repeat
                && def.Repetition!.Count.Kind != RepetitionCountKind.Count)
            {
                repetitionDefinition = def.Repetition;
                break;
            }
        }

        var repetition = repetitionDefinition!;
        ushort repetitionTrackCount = repetition.TrackCount();

        // Determine the number of repetitions
        ushort numRepetitions;
        if (!autoFitContainerSize.HasValue)
        {
            numRepetitions = 1;
        }
        else
        {
            float innerContainerSize = autoFitContainerSize.Value;
            float? parentSize = innerContainerSize;

            float nonRepeatingTrackUsedSpace = 0.0f;
            foreach (var trackDef in template)
            {
                if (trackDef.Kind == GridTemplateComponentKind.Single)
                {
                    nonRepeatingTrackUsedSpace +=
                        TrackDefiniteValue(trackDef.Single, parentSize, resolveCalcValue);
                }
                else if (trackDef.Repetition!.Count.Kind == RepetitionCountKind.Count)
                {
                    float sum = 0.0f;
                    foreach (var sizingFunction in trackDef.Repetition.Tracks)
                    {
                        sum += TrackDefiniteValue(sizingFunction, parentSize, resolveCalcValue);
                    }

                    nonRepeatingTrackUsedSpace += sum * trackDef.Repetition.Count.Count;
                }
            }

            float gapSize = style.Gap.GetAbs(axis).ResolveOrZero(innerContainerSize, resolveCalcValue);

            // Compute the amount of space that a single repetition of the repeated track list takes
            float perRepetitionTrackUsedSpace = 0.0f;
            foreach (var sizingFunction in repetition.Tracks)
            {
                perRepetitionTrackUsedSpace += TrackDefiniteValue(sizingFunction, parentSize, resolveCalcValue);
            }

            // The first repetition is special-cased because the number of gaps in it depends on the
            // number of non-repeating tracks in the template.
            int gapCount = nonAutoRepeatingTrackCount + repetitionTrackCount;
            gapCount = gapCount > 0 ? gapCount - 1 : 0;
            float firstRepetitionAndNonRepeatingTracksUsedSpace =
                nonRepeatingTrackUsedSpace + perRepetitionTrackUsedSpace + (gapCount * gapSize);

            // If a single repetition already overflows the container then the repetition count is 1
            // (the number of repetitions is floored at 1).
            if (firstRepetitionAndNonRepeatingTracksUsedSpace > innerContainerSize)
            {
                numRepetitions = 1;
            }
            else
            {
                float perRepetitionGapUsedSpace = repetitionTrackCount * gapSize;
                float perRepetitionUsedSpace = perRepetitionTrackUsedSpace + perRepetitionGapUsedSpace;
                float numRepetitionThatFit =
                    (innerContainerSize - firstRepetitionAndNonRepeatingTracksUsedSpace)
                    / perRepetitionUsedSpace;

                numRepetitions = autoFitStrategy switch
                {
                    AutoRepeatStrategy.MaxRepetitionsThatDoNotOverflow =>
                        (ushort)((ushort)Sys.Floor(numRepetitionThatFit) + 1),
                    _ => (ushort)((ushort)Sys.Ceil(numRepetitionThatFit) + 1),
                };
            }
        }

        ushort gridTemplateTrackCount =
            (ushort)(nonAutoRepeatingTrackCount + (repetitionTrackCount * numRepetitions));
        return (numRepetitions, gridTemplateTrackCount);
    }

    /// <summary>
    /// Resolve the track sizing functions of explicit tracks, automatically created tracks, and
    /// gutters given a set of track counts and all of the relevant styles.
    /// </summary>
    public static void InitializeGridTracks(
        List<GridTrack> tracks,
        TrackCounts counts,
        IGridContainerStyle style,
        AbsoluteAxis axis,
        Func<int, bool> trackHasItems)
    {
        IReadOnlyList<GridTemplateComponent>? trackTemplate;
        IReadOnlyList<TrackSizingFunction> autoTracks;
        LengthPercentage gap;
        if (axis == AbsoluteAxis.Horizontal)
        {
            trackTemplate = style.GridTemplateColumns;
            autoTracks = style.GridAutoColumns;
            gap = style.Gap.Width;
        }
        else
        {
            trackTemplate = style.GridTemplateRows;
            autoTracks = style.GridAutoRows;
            gap = style.Gap.Height;
        }

        // Clear the list (in case this is a re-layout), reserve space for all tracks ahead of time to
        // reduce allocations, and push the initial gutter.
        tracks.Clear();
        tracks.Capacity = Math.Max(tracks.Capacity, (counts.Len() * 2) + 1);
        tracks.Add(GridTrack.Gutter(gap));

        int autoTrackCount = autoTracks.Count;
        ushort nonAutoRepeatingTrackCount = 0;
        if (trackTemplate is not null)
        {
            foreach (var trackDef in trackTemplate)
            {
                nonAutoRepeatingTrackCount += NonAutoRepeatingTracks(trackDef);
            }
        }

        // Create negative implicit tracks
        if (counts.NegativeImplicit > 0)
        {
            if (autoTrackCount == 0)
            {
                CreateImplicitTracks(tracks, counts.NegativeImplicit, new AutoTrackCycle(), gap);
            }
            else
            {
                int offset = autoTrackCount - (counts.NegativeImplicit % autoTrackCount);
                CreateImplicitTracks(
                    tracks, counts.NegativeImplicit, new AutoTrackCycle(autoTracks, offset), gap);
            }
        }

        int currentTrackIndex = counts.NegativeImplicit;

        // Create explicit tracks.
        // An explicit check against the count (rather than just relying on trackTemplate being empty)
        // is required here because a count of zero can result from an invalid track template, in
        // which case it should be ignored.
        if (counts.Explicit > 0 && trackTemplate is not null)
        {
            foreach (var trackSizingFunction in trackTemplate)
            {
                if (trackSizingFunction.Kind == GridTemplateComponentKind.Single)
                {
                    var sizingFunction = trackSizingFunction.Single;
                    tracks.Add(GridTrack.New(
                        sizingFunction.MinSizingFunction(), sizingFunction.MaxSizingFunction()));
                    tracks.Add(GridTrack.Gutter(gap));
                    currentTrackIndex += 1;
                    continue;
                }

                var repeat = trackSizingFunction.Repetition!;
                if (repeat.Count.Kind == RepetitionCountKind.Count)
                {
                    int total = repeat.TrackCount() * repeat.Count.Count;
                    for (int i = 0; i < total; i++)
                    {
                        var sizingFunction = repeat.Tracks[i % repeat.Tracks.Count];
                        tracks.Add(GridTrack.New(
                            sizingFunction.MinSizingFunction(), sizingFunction.MaxSizingFunction()));
                        tracks.Add(GridTrack.Gutter(gap));
                        currentTrackIndex += 1;
                    }

                    continue;
                }

                int autoRepeatedTrackCount = counts.Explicit - nonAutoRepeatingTrackCount;
                for (int i = 0; i < autoRepeatedTrackCount; i++)
                {
                    var trackDef = repeat.Tracks[i % repeat.Tracks.Count];
                    var track = GridTrack.New(trackDef.MinSizingFunction(), trackDef.MaxSizingFunction());
                    var gutter = GridTrack.Gutter(gap);

                    // Auto-fit tracks that don't contain items should be collapsed.
                    if (repeat.Count.Kind == RepetitionCountKind.AutoFit && !trackHasItems(currentTrackIndex))
                    {
                        track.Collapse();
                        gutter.Collapse();
                    }

                    tracks.Add(track);
                    tracks.Add(gutter);

                    currentTrackIndex += 1;
                }

                // Is this auto-repeat at the very end of the track list?
                bool isLast = currentTrackIndex == counts.Len();

                // When collapsing auto-fit tracks (in the loop just above) we collapse the gutter
                // after collapsed tracks but not the gutter before. That is correct so long as there
                // is another non-collapsed track later in the track list. If the auto-fit repeat is
                // at the very end there is no such track, so iterate backwards collapsing tracks and
                // gutters until the first non-collapsed track.
                if (repeat.Count.Kind == RepetitionCountKind.AutoFit && isLast)
                {
                    for (int i = tracks.Count - 1; i >= 0; i--)
                    {
                        var previousTrack = tracks[i];
                        if (previousTrack.Kind == GridTrackKind.Track && !previousTrack.IsCollapsed)
                        {
                            break;
                        }

                        previousTrack.Collapse();
                    }
                }
            }
        }

        int gridAreaTracks = counts.NegativeImplicit + counts.Explicit - currentTrackIndex;

        // Create positive implicit tracks
        int positiveCount = counts.PositiveImplicit + gridAreaTracks;
        if (autoTrackCount == 0)
        {
            CreateImplicitTracks(tracks, positiveCount, new AutoTrackCycle(), gap);
        }
        else
        {
            CreateImplicitTracks(tracks, positiveCount, new AutoTrackCycle(autoTracks, 0), gap);
        }

        // Mark first and last grid lines as collapsed
        tracks[0].Collapse();
        tracks[^1].Collapse();
    }

    private static ushort NonAutoRepeatingTracks(GridTemplateComponent trackDef)
    {
        if (trackDef.Kind == GridTemplateComponentKind.Single)
        {
            return 1;
        }

        var repeat = trackDef.Repetition!;
        return repeat.Count.Kind == RepetitionCountKind.Count
            ? (ushort)(repeat.Count.Count * repeat.TrackCount())
            : (ushort)0;
    }

    /// <summary>
    /// Treat each track as its max track sizing function if that is definite, or as its minimum
    /// track sizing function otherwise, flooring the max by the min if both are definite.
    /// </summary>
    private static float TrackDefiniteValue(
        TrackSizingFunction sizingFunction,
        float? parentSize,
        CalcResolver calcResolver)
    {
        float? maxSize = sizingFunction.Max.DefiniteValue(parentSize, calcResolver);
        float? minSize = sizingFunction.Min.DefiniteValue(parentSize, calcResolver);
        float? result = maxSize.HasValue ? maxSize.Value.MaybeMax(minSize) : minSize;
        return result!.Value;
    }

    /// <summary>Utility for the repeating logic of creating implicit tracks.</summary>
    private static void CreateImplicitTracks(
        List<GridTrack> tracks,
        int count,
        AutoTrackCycle autoTracksIter,
        LengthPercentage gap)
    {
        for (int i = 0; i < count; i++)
        {
            var trackDef = autoTracksIter.Next();
            tracks.Add(GridTrack.New(trackDef.MinSizingFunction(), trackDef.MaxSizingFunction()));
            tracks.Add(GridTrack.Gutter(gap));
        }
    }

    /// <summary>
    /// An infinite cycling iterator over the grid-auto-* track list, standing in for Rust's
    /// <c>iter().cycle().skip(n)</c>. With no track list it yields <c>auto</c> forever, matching
    /// <c>core::iter::repeat(TrackSizingFunction::AUTO)</c>.
    /// </summary>
    private sealed class AutoTrackCycle
    {
        private readonly IReadOnlyList<TrackSizingFunction>? _tracks;
        private int _index;

        public AutoTrackCycle()
        {
            _tracks = null;
            _index = 0;
        }

        public AutoTrackCycle(IReadOnlyList<TrackSizingFunction> tracks, int skip)
        {
            _tracks = tracks;
            _index = tracks.Count == 0 ? 0 : skip % tracks.Count;
        }

        public TrackSizingFunction Next()
        {
            if (_tracks is null || _tracks.Count == 0)
            {
                return TrackSizingFunction.Auto;
            }

            var value = _tracks[_index];
            _index = (_index + 1) % _tracks.Count;
            return value;
        }
    }
}
